Some adjustments due to recent re-organization. 	* lisp/Makefile.am: Change order of dependencies. 	* list/emacs.scm: Update return-type syntax.  Add imports. 	* lang/ELisp.java: Also catch NoClassDefFoundError.
git-svn-id: svn://sourceware.org/svn/kawa/trunk@8847 5e0a886f-7f45-49c5-bc19-40643649e37f